# Generated by Django 4.2.6 on 2023-11-30 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fortiApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
