# Generated by Django 4.2.6 on 2023-11-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortiApi', '0003_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Humas', 'Humas'), ('Mahasiswa', 'Mahasiswa'), ('Dosen', 'Dosen')], max_length=10),
        ),
    ]
