# Generated by Django 4.2.6 on 2023-11-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortiApi', '0004_user_first_name_user_last_name_alter_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
