# Generated by Django 4.2.6 on 2023-12-01 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fortiApi', '0007_alter_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='content_type',
            field=models.CharField(choices=[('Post', 'Post'), ('Replies', 'Replies')], default='Post'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default='Like'),
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(default='comment', max_length=250),
        ),
        migrations.AddField(
            model_name='post',
            name='user_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='fortiApi.user'),
        ),
        migrations.AddField(
            model_name='replies',
            name='post_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fortiApi.post'),
        ),
        migrations.AddField(
            model_name='replies',
            name='user_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='fortiApi.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Humas', 'Humas'), ('Mahasiswa', 'Mahasiswa'), ('Dosen', 'Dosen')]),
        ),
    ]
