# Generated by Django 4.2.6 on 2023-12-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortiApi', '0010_alter_post_user_id_alter_postfeedback_feedback_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Replies',
            new_name='Reply',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=30),
        ),
    ]
