# Generated by Django 4.2.6 on 2023-12-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortiApi', '0012_rename_nomor_induk_user_identity_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('humas', 'Humas'), ('mahasiswa', 'Mahasiswa'), ('dosen', 'Dosen')]),
        ),
    ]
