# Generated by Django 4.2.6 on 2023-12-19 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fortiApi', '0014_alter_post_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_id',
        ),
    ]
