# Generated by Django 4.2.6 on 2023-12-19 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fortiApi', '0017_rename_user_id_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postfeedback',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postfeedback',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='repliesfeedback',
            old_name='replies_id',
            new_name='replies',
        ),
        migrations.RenameField(
            model_name='repliesfeedback',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='fortiApi.user'),
        ),
    ]
