# Generated by Django 4.2.6 on 2023-12-19 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fortiApi', '0018_rename_post_id_postfeedback_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default='indi', on_delete=django.db.models.deletion.DO_NOTHING, to='fortiApi.user'),
        ),
    ]
