# Generated by Django 4.2.6 on 2023-12-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortiApi', '0022_remove_postfeedback_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repliesfeedback',
            name='feedback_type',
            field=models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default='Like'),
        ),
    ]
