# Generated by Django 4.2.6 on 2023-12-20 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fortiApi', '0023_alter_repliesfeedback_feedback_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='feedback',
        ),
        migrations.AddField(
            model_name='postfeedback',
            name='post',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='fortiApi.post'),
        ),
        migrations.AddField(
            model_name='repliesfeedback',
            name='post',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='fortiApi.post'),
        ),
        migrations.AddField(
            model_name='repliesfeedback',
            name='replies',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='fortiApi.reply'),
        ),
    ]
