# Generated by Django 4.2.6 on 2023-12-20 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fortiApi', '0026_post_category_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.RemoveField(
            model_name='repliesfeedback',
            name='post',
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_post', to='fortiApi.user'),
        ),
        migrations.AlterField(
            model_name='postfeedback',
            name='feedback_type',
            field=models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], max_length=10),
        ),
        migrations.AlterField(
            model_name='postfeedback',
            name='post',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='fortiApi.post'),
        ),
        migrations.AlterField(
            model_name='postfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_feedback', to='fortiApi.user'),
        ),
        migrations.AlterField(
            model_name='repliesfeedback',
            name='feedback_type',
            field=models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default='Like', max_length=10),
        ),
        migrations.AlterField(
            model_name='repliesfeedback',
            name='replies',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='fortiApi.reply'),
        ),
        migrations.AlterField(
            model_name='repliesfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies_feedback', to='fortiApi.user'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='fortiApi.post'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_reply', to='fortiApi.user'),
        ),
    ]
