# Generated by Django 4.2.6 on 2023-12-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortiApi', '0027_delete_employee_remove_repliesfeedback_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='postfeedback',
            name='feedback_type',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10),
        ),
        migrations.AlterField(
            model_name='repliesfeedback',
            name='feedback_type',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], default='Like', max_length=10),
        ),
    ]
