# Generated by Django 4.2.6 on 2023-12-20 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fortiApi', '0029_alter_post_updated_at_alter_postfeedback_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_post', to='fortiApi.user'),
        ),
        migrations.AlterField(
            model_name='postfeedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_feedback', to='fortiApi.user'),
        ),
        migrations.AlterField(
            model_name='repliesfeedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies_feedback', to='fortiApi.user'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_reply', to='fortiApi.user'),
        ),
    ]
