# Generated by Django 4.2.6 on 2023-12-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortiApi', '0030_alter_post_user_alter_postfeedback_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identity_number',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
